# Generated by Django 4.2 on 2023-04-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hongapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hong",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "hong",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20)),
                ("pwd", models.CharField(max_length=20)),
                ("c_date", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="Sleep",
        ),
    ]
