# Generated by Django 4.2 on 2023-04-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hongapp", "0002_hong_user_delete_sleep"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
