# Generated by Django 4.2 on 2023-04-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sleep",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Colunm_1", models.CharField(max_length=20)),
                ("Colunm_2", models.CharField(max_length=20)),
                ("Colunm_3", models.CharField(max_length=20)),
                ("Colunm_4", models.CharField(max_length=20)),
                ("Colunm_5", models.CharField(max_length=20)),
                ("Colunm_6", models.FloatField()),
                ("Colunm_7", models.CharField(max_length=20)),
                ("Colunm_8", models.CharField(max_length=40)),
                ("Colunm_9", models.CharField(max_length=40)),
                ("Colunm_10", models.FloatField()),
                ("Colunm_11", models.FloatField()),
                ("Colunm_12", models.CharField(max_length=20)),
                ("Colunm_13", models.FloatField()),
                ("Colunm_14", models.CharField(max_length=20)),
                ("Colunm_15", models.CharField(max_length=20)),
                ("Colunm_16", models.CharField(max_length=20)),
                ("Colunm_17", models.CharField(max_length=20)),
                ("Colunm_18", models.CharField(max_length=20)),
                ("Colunm_19", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "sleep",
                "managed": False,
            },
        ),
    ]
